
mybatis-plus:
  mapper-locations: classpath:sysUser/mapper/*Mapper.xml
  type-aliases-package: com.bzgwl.mybatis_plus.sysUser.entity
server:
  port: 9000

spring:
  activiti:
    db-history-used: true  #使用历史表，如果不配置，则工程启动后可以检查数据库，只建立了17张表，历史表没有建立
    history-level: full    #记录全部历史操作
    database-schema-update: true    #自动建表
#    flase： 默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常。
#    true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。
#    create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）。
#    drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎

    check-process-definitions: false # 自动部署验证设置:true-开启（默认）、false-关闭  在resource目录下添加processes文件夹，并且文件夹不能为空
#    main:
#      allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
    database-schema: atc  #置建表策略，如果没有表，自动创建表  修改这个地方为大写
